### ISSUE TITLE
Do not overwrite the label of tab group folder

### ISSUE THREAD

**Issue by gqqnbig** [PolarGoose/DirectoryOpus-TabLabelizer-plugin#2]
![dopus_AK18sN3RzV](https://github.com/PolarGoose/DirectoryOpus-TabLabelizer-plugin/assets/614159/6cdd7f92-1223-4519-bc21-ede088ecee9a)

My Latex tab group defines two folders, Latex Installation and Latex Output. After I open this tab group, I expect the tab labels to be my defined names, but it seems DirectoryOpus TabLabelizer plugin overwrites the names to full paths.

Can you not ovewrite labels  of tab group folder?

Thank you.

**Comment by PolarGoose** [comment]
@gqqnbig,

Thank you for the bug report.

> Can you not ovewrite labels of tab group folder?

I have never used the **Tab Groups** functionality. I don't see an easy way how I could implement it.

**Comment by gqqnbig** [comment]
I coded a preliminary version at https://resource.dopus.com/t/show-tab-group-name-in-lister-title/36446/9?u=gqqnbig 😄 

I don't intend to push too many requests as I'm using the group name script on my home computer, and using your script on my laptop. The two scripts are oblivious to each other.

It's your call whether you leave the issue as future work or close it for now.
